# Generated by Django 4.1.5 on 2023-03-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('question', models.CharField(choices=[('nm', 'What is your favourite name ?'), ('no', 'What is your favourite number ?'), ('th', 'What is your favourtie thing ?')], max_length=2)),
                ('answer', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=5)),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
    ]
