# Generated by Django 4.1.5 on 2023-03-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registery',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registery',
            name='question',
            field=models.CharField(choices=[('nm', 'What is your favourite name ?'), ('no', 'What is your favourite number ?'), ('th', 'What is your favourtie thing ?')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registery',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=11),
        ),
    ]
