# Generated by Django 4.1.5 on 2023-03-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_registery_answer_alter_registery_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registery',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], max_length=11),
        ),
    ]
