# Generated by Django 4.1.7 on 2023-03-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_registery_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registery',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registery',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registery',
            name='username',
        ),
        migrations.AddField(
            model_name='registery',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
