# Generated by Django 4.1.5 on 2023-03-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31, unique=True)),
                ('password', models.CharField(max_length=121)),
                ('role', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneno', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=31)),
                ('question', models.CharField(max_length=41)),
                ('answer', models.CharField(max_length=21)),
                ('status', models.CharField(default='active', max_length=11)),
            ],
        ),
    ]
